-- 주의 사항: 
-- COMMIT은 한번만 해도 모든 데이터 테이블이 저장 된다.
-- ',' 과 ';' 유의할 것.

-- 이용자 테이블
DROP TABLE CUSTOMER_INFO;
DROP TABLE MASTER_INFO;
DROP TABLE KOREAN_FOOD;
DROP TABLE CIHNA_FOOD;
DROP TABLE JAPANESE_FOOD;
DROP TABLE FAST_FOOD;
DROP TABLE YA_SICK;
DROP TABLE WESTERN_FOOD;


SELECT * FROM CUSTOMER_INFO;
SELECT * FROM MASTER_INFO;
SELECT * FROM KOREAN_FOOD;
SELECT * FROM CIHNA_FOOD;
SELECT * FROM JAPANESE_FOOD;
SELECT * FROM FAST_FOOD;
SELECT * FROM YA_SICK;
SELECT * FROM WESTERN_FOOD;



CREATE TABLE CUSTOMER_INFO(
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_PW VARCHAR(20) NOT NULL,
    CUSTOMER_NAME VARCHAR(20) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Addr VARCHAR(20) NOT NULL,
    Birth CHAR(6) NOT NULL,
    Email VARCHAR(20),	
    monthFee NUMBER(5) NOT NULL
);
INSERT INTO CUSTOMER_INFO VALUES('USER1', '1234', '사용자1', '010', '서울시', '1998', 'NAVER', 5000);
INSERT INTO CUSTOMER_INFO VALUES('USER2', '2234', '사용자2', '011', '수원시', '1999', '', 15000);
INSERT INTO CUSTOMER_INFO VALUES('USER3', '3234', '사용자3', '012', '부산시', '2000', 'NAVER', 5000);
INSERT INTO CUSTOMER_INFO VALUES('USER4', '4234', '사용자4', '013', '서울시', '1998', 'NAVER', 5000);
INSERT INTO CUSTOMER_INFO VALUES('USER5', '5234', '사용자5', '014', '수원시', '1999', '', 15000);
INSERT INTO CUSTOMER_INFO VALUES('USER6', '6234', '사용자6', '015', '부산시', '2000', 'NAVER', 5000);
INSERT INTO CUSTOMER_INFO VALUES('USER7', '7234', '사용자7', '016', '서울시', '1998', 'NAVER', 5000);
INSERT INTO CUSTOMER_INFO VALUES('USER8', '8234', '사용자8', '017', '수원시', '1999', '', 15000);
INSERT INTO CUSTOMER_INFO VALUES('USER9', '9234', '사용자9', '018', '부산시', '2000', 'NAVER', 5000);
INSERT INTO CUSTOMER_INFO VALUES('USER0', '1000', '사용자0', '999', '인천시', '2023', '@@@@', 15000);


-- 관리자 테이블
-- NULL로 표기한 부분은 잘 모르겠어서 표기.
CREATE TABLE MASTER_INFO(
    MASTER_ID VARCHAR(20) PRIMARY KEY,
    MASTER_PW VARCHAR(20) NOT NULL,
    MASTER_NAME VARCHAR(20) NOT NULL,
    MASTER_STORE VARCHAR(20) NOT NULL,
    TOTALSALES VARCHAR(20) NOT NULL,
    BIZNUM VARCHAR(20) NOT NULL
);
INSERT INTO MASTER_INFO VALUES('MASTER1', '1234', '영업주1', 'NULL', 'NULL', '사업자번호1');
INSERT INTO MASTER_INFO VALUES('MASTER2', '2234', '영업주2', 'NULL', 'NULL', '사업자번호2');
INSERT INTO MASTER_INFO VALUES('MASTER3', '3234', '영업주3', 'NULL', 'NULL', '사업자번호3');
INSERT INTO MASTER_INFO VALUES('MASTER4', '4234', '영업주4', 'NULL', 'NULL', '사업자번호4');
INSERT INTO MASTER_INFO VALUES('MASTER5', '5234', '영업주5', 'NULL', 'NULL', '사업자번호5');
INSERT INTO MASTER_INFO VALUES('MASTER6', '6234', '영업주6', 'NULL', 'NULL', '사업자번호6');
INSERT INTO MASTER_INFO VALUES('MASTER7', '7234', '영업주7', 'NULL', 'NULL', '사업자번호7');
INSERT INTO MASTER_INFO VALUES('MASTER8', '8234', '영업주8', 'NULL', 'NULL', '사업자번호8');
INSERT INTO MASTER_INFO VALUES('MASTER9', '9234', '영업주9', 'NULL', 'NULL', '사업자번호9');
INSERT INTO MASTER_INFO VALUES('MASTER0', '0001', '영업주0', 'NULL', 'NULL', '000000');



-- 한식 테이블, COUNT는 자바에서 구현
CREATE TABLE KOREAN_FOOD(
    MENU_NAME VARCHAR(10) UNIQUE,
    PRICE     NUMBER(6)   NOT NULL,
    CNT       NUMBER(3)   
);
INSERT INTO KOREAN_FOOD VALUES ('KSOUP', 7000, NULL);
INSERT INTO KOREAN_FOOD VALUES ('KROAST', 8000, NULL);
INSERT INTO KOREAN_FOOD VALUES ('KSNACK', 5000, NULL);
INSERT INTO KOREAN_FOOD VALUES ('KMEAT', 10000, NULL);

-- 중식 테이블
CREATE TABLE CIHNA_FOOD(
    MENU_NAME VARCHAR(10) UNIQUE,
    PRICE     NUMBER(6)   NOT NULL,
    CNT       NUMBER(3)   
);
INSERT INTO CIHNA_FOOD VALUES ('CNOODLE', 7000, NULL);
INSERT INTO CIHNA_FOOD VALUES ('CFRIED', 8000, NULL);
INSERT INTO CIHNA_FOOD VALUES ('CSOUP', 5000, NULL);
INSERT INTO CIHNA_FOOD VALUES ('CROAST', 10000, NULL);

-- 일식 테이블
CREATE TABLE JAPANESE_FOOD(
    MENU_NAME VARCHAR(10) UNIQUE,
    PRICE     NUMBER(6)   NOT NULL,
    CNT       NUMBER(3) 
);
INSERT INTO JAPANESE_FOOD VALUES ('JRAMEN', 5000, NULL);
INSERT INTO JAPANESE_FOOD VALUES ('JSUSI', 10000, NULL);
INSERT INTO JAPANESE_FOOD VALUES ('JROAST', 8000, NULL);
INSERT INTO JAPANESE_FOOD VALUES ('JRICE', 9000, NULL);

-- 패스트푸드 테이블
CREATE TABLE FAST_FOOD(
    MENU_NAME VARCHAR(10) UNIQUE,
    PRICE     NUMBER(6)   NOT NULL,
    CNT       NUMBER(3) 
);
INSERT INTO FAST_FOOD VALUES ('FBURGER', 5000, NULL);
INSERT INTO FAST_FOOD VALUES ('FPIZZA', 12000, NULL);
INSERT INTO FAST_FOOD VALUES ('FDOG', 3000, NULL);
INSERT INTO FAST_FOOD VALUES ('FTACO', 5000, NULL);

-- 야식 테이블
CREATE TABLE YA_SICK(
    MENU_NAME VARCHAR(10) UNIQUE,
    PRICE     NUMBER(6)   NOT NULL,
    CNT       NUMBER(3)
);
INSERT INTO YA_SICK VALUES ('NMEAT', 18000, NULL);
INSERT INTO YA_SICK VALUES ('NORGAN', 18000, NULL);
INSERT INTO YA_SICK VALUES ('NSEAFOOD', 22000, NULL);
INSERT INTO YA_SICK VALUES ('NCHIKEN', 18000, NULL);

-- 양식 테이블
CREATE TABLE WESTERN_FOOD(
    MENU_NAME VARCHAR(10) UNIQUE,
    PRICE     NUMBER(6)   NOT NULL,
    CNT       NUMBER(3)
);
INSERT INTO WESTERN_FOOD VALUES ('WSALADE', 18000, NULL);
INSERT INTO WESTERN_FOOD VALUES ('WNOODLE', 18000, NULL);
INSERT INTO WESTERN_FOOD VALUES ('WMEAT', 22000, NULL);
INSERT INTO WESTERN_FOOD VALUES ('WSOUP', 18000, NULL);


-- 점포 테이블. 아직 연결 구현 X
CREATE TABLE STORE(
    KOREAN_FOOD	    VARCHAR(30)	NOT NULL,
    CIHNA_FOOD	    VARCHAR(30)	NOT NULL,
    JAPANESE_FOOD	VARCHAR(30)	NOT NULL,
    FAST_FOOD	    VARCHAR(30)	NOT NULL,
    WESTERN_FOOD	VARCHAR(30)	NOT NULL,
    YA_SICK	        VARCHAR(30)	NOT NULL
);
