DROP TABLE ORDER_INFO;
DROP SEQUENCE ORDNUM_SEQ;
SELECT * FROM ORDER_INFO;

CREATE SEQUENCE ORDNUM_SEQ
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999
	MINVALUE 1
	NOCYCLE;

CREATE TABLE ORDER_INFO (
    ORDER_NUM NUMBER PRIMARY KEY,
    DATE_NUM DATE NULL,
    MENU_NAME VARCHAR2(30), -- REFERENCES FOOD (MENU_NAME),
    PRICE NUMBER(5), -- REFERENCES FOOD (PRICE)
    PAYMENT_OPTION VARCHAR2(20) CHECK (PAYMENT_OPTION = '카드' OR PAYMENT_OPTION = '현금'),
    OPT VARCHAR2(30),
    AMOUNT NUMBER(2) NOT NULL,
    TOTAL_PAYMENT NUMBER(8)
); 
INSERT INTO ORDER_INFO VALUES(ORDNUM_SEQ.NEXTVAL, SYSDATE, 'KSOUP', 8000, '카드', NULL, 2, NULL);
INSERT INTO ORDER_INFO VALUES(ORDNUM_SEQ.NEXTVAL, SYSDATE, 'KMEAT', 12000, '현금', NULL, 2, NULL);

-- 쿼리문 TOTAL_PAYMENT UPDATE
-- 추가 기능: ORDER_NUM 에 시퀀스 넣어서 하나하나 자동화 하기
SELECT AMOUNT * PRICE FROM ORDER_INFO;
UPDATE ORDER_INFO SET TOTAL_PAYMENT = AMOUNT * PRICE WHERE ORDER_NUM = 1;
