DROP TABLE ORDER_INFO;
DROP SEQUENCE ORDNUM_SEQ;
SELECT * FROM ORDER_INFO;
commit;

CREATE SEQUENCE ORDNUM_SEQ
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999
	MINVALUE 1
	NOCYCLE;

CREATE TABLE ORDER_INFO (
    -- ORDER_NUM NUMBER PRIMARY KEY,
    MENU_NAME VARCHAR2(30), REFERENCES FOOD (MENU_NAME),
    PRICE NUMBER(5), REFERENCES FOOD (PRICE),
    DEILVERY_TYPE VACHAR2(6) CHECK (DEILVERY_TYPE = '배달' OR DEILVERY_TYPE = '포장'),
    PAYMENT_OPTION VARCHAR2(6) CHECK (PAYMENT_OPTION = '카드' OR PAYMENT_OPTION = '현금'),
    OPT VARCHAR2(15) CHECK (OPT = '나무젓가락' OR OPT = 'X'),
    AMOUNT NUMBER(2) NOT NULL,
    TOTAL_PAYMENT NUMBER(8),
    DATE_NUM DATE NULL
); 
-- INSERT INTO ORDER_INFO VALUES(ORDNUM_SEQ.NEXTVAL, SYSDATE, 'KSOUP', 8000, '카드', NULL, 2, NULL, SYSDATE);


-- 쿼리문 

-- UPDATE
-- TOTAL_PAYMENT : ORDER_NUM 에 시퀀스 넣어서 하나하나 자동화 하기
SELECT AMOUNT * PRICE FROM ORDER_INFO;
UPDATE ORDER_INFO SET TOTAL_PAYMENT = AMOUNT * PRICE WHERE ORDER_NUM = 1;

-- INSERT
-- 옵션(OPT) : 자바에서 입력하여 NULL 값에 추가
INSERT ORDER_INFO SET OPT 